### ISSUE TITLE
Work Package: Filter the dashboard by `provider`

### ISSUE THREAD

**Issue by mmaelicke** [TeSKA-LMZ/teska-monitor#11]
**Dauer: 2 Std**

### Description

Right now, all data is loaded into the dashboard, and data from different schools (== `providers`)  is mixed up. We need a dropdown, that specifies a current `provider` and filters all data.

**This PR needs some discussion, as the filter can not be easily applied to the 'live data' (in the first row)**

### Tasks

- [ ] add a `db.get_providers` to load all unique provider names in the db. This list should populate the dropdown
- [ ] add the dropdown to the layout
- [ ] inject the dropdown into the `update_history_graph` callback to apply the filter
- [ ] Make the changes visible by dynamically changing the title of the Graph
